ALTER TABLE learners
    DROP COLUMN IF EXISTS university,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(50),
    ADD COLUMN IF NOT EXISTS location VARCHAR(255),
    ADD COLUMN IF NOT EXISTS region VARCHAR(255),
    ADD COLUMN IF NOT EXISTS institution VARCHAR(255);
